[project]
name = "tensor-stats-helper"      
version = "3.2.4"
description = "Quick tensor statistics utilities"
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
